apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  namespace: level-3
  name: repo-sync
spec:
  git:
    auth: none
    branch: main
    dir: resources/level-3
    repo: https://github.com/tomasaschan/config-sync-repro
  sourceFormat: unstructured
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-management
  namespace: level-3
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    namespace: config-management-system
    name: ns-reconciler-level-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
